DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/camera-kernel
KBUILD_DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/camera-kernel

dtbo-$(CONFIG_ARCH_WAIPIO) += ../waipio-camera.dtbo
dtbo-$(CONFIG_MACH_SONY_PDX223) += waipio-camera-sensor-nagara-pdx223.dtbo 
dtbo-$(CONFIG_MACH_SONY_PDX224) += waipio-camera-sensor-nagara-pdx224.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
